
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A hyperlocal weather forecast AI agent.
 *
 * - hyperlocalForecast - A function that handles the hyperlocal weather forecast process.
 * - HyperlocalForecastInput - The input type for the hyperlocalForecast function.
 * - HyperlocalForecastOutput - The return type for the hyperlocalForecast function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const HyperlocalForecastInputSchema = z.object({
  location: z
    .string()
    .describe(
      'The location for which to generate a hyperlocal weather forecast. This can be an address or latitude/longitude coordinates.'
    ),
});
export type HyperlocalForecastInput = z.infer<typeof HyperlocalForecastInputSchema>;

const HyperlocalForecastOutputSchema = z.object({
  forecast: z.string().describe('A detailed hyperlocal weather forecast.'),
  locationName: z.string().describe('The name of the location.'),
});
export type HyperlocalForecastOutput = z.infer<typeof HyperlocalForecastOutputSchema>;

export async function hyperlocalForecast(input: HyperlocalForecastInput): Promise<HyperlocalForecastOutput> {
  return hyperlocalForecastFlow(input);
}

const prompt = ai.definePrompt({
  name: 'hyperlocalForecastPrompt',
  input: {schema: HyperlocalForecastInputSchema},
  output: {schema: HyperlocalForecastOutputSchema},
  prompt: `You are an expert meteorologist specializing in hyperlocal weather forecasts.

You will use the location to generate a detailed and accurate weather forecast for that specific area.

Location: {{{location}}}

Include the location name and the forecast.
`,
});

const hyperlocalForecastFlow = ai.defineFlow(
  {
    name: 'hyperlocalForecastFlow',
    inputSchema: HyperlocalForecastInputSchema,
    outputSchema: HyperlocalForecastOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
