
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that provides structured hourly and daily weather forecasts.
 *
 * - structuredWeatherForecast - A function that returns detailed structured weather data.
 * - StructuredWeatherForecastInput - The input type for the structuredWeatherForecast function.
 * - StructuredWeatherForecastOutput - The return type for the structuredWeatherForecast function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const StructuredWeatherForecastInputSchema = z.object({
  location: z
    .string()
    .describe(
      'The location for which to generate a structured weather forecast. This can be an address or latitude/longitude coordinates.'
    ),
  referenceTodayHigh: z
    .number()
    .optional()
    .describe(
      'An optional reference high temperature for today in Celsius. If provided, the daily forecast for today should align with this high, and hourly temperatures should plausibly lead to it.'
    ),
});
export type StructuredWeatherForecastInput = z.infer<typeof StructuredWeatherForecastInputSchema>;

const HourlyForecastItemSchema = z.object({
  time: z.string().describe("The specific time for the forecast (e.g., '3 PM', '10:00')."),
  temperature: z.number().describe('The temperature in Celsius.'),
  description: z.string().describe('A brief textual description of the weather conditions.'),
  iconName: z.string().describe("A simple weather condition name from the allowed list (e.g., 'Sunny', 'Partly Cloudy', 'Rain'). This will be used to pick an icon."),
});

const DailyForecastItemSchema = z.object({
  day: z.string().describe("The day of the week or relative day (e.g., 'Mon', 'Today', 'Tomorrow')."),
  high: z.number().describe('The high temperature for the day in Celsius.'),
  low: z.number().describe('The low temperature for the day in Celsius.'),
  description: z.string().describe('A brief textual description of the weather conditions for the day.'),
  iconName: z.string().describe("A simple weather condition name from the allowed list (e.g., 'Sunny', 'Partly Cloudy', 'Rain'). This will be used to pick an icon."),
});

const StructuredWeatherForecastOutputSchema = z.object({
  hourly: z.array(HourlyForecastItemSchema).describe('An array of 12 hourly forecast items.'),
  daily: z.array(DailyForecastItemSchema).describe('An array of 7 daily forecast items.'),
  locationName: z.string().describe('The name of the location for which the forecast was generated.'),
});
export type StructuredWeatherForecastOutput = z.infer<typeof StructuredWeatherForecastOutputSchema>;

export async function structuredWeatherForecast(input: StructuredWeatherForecastInput): Promise<StructuredWeatherForecastOutput> {
  return structuredWeatherForecastFlow(input);
}

const prompt = ai.definePrompt({
  name: 'structuredWeatherForecastPrompt',
  input: {schema: StructuredWeatherForecastInputSchema},
  output: {schema: StructuredWeatherForecastOutputSchema},
  prompt: `You are a weather API. For the given location, provide a structured weather forecast.

Location: {{{location}}}

{{#if referenceTodayHigh}}
Important: For "Today's" forecast in the daily items, the high temperature MUST be {{{referenceTodayHigh}}}°C.
The hourly forecast for today should show temperatures that are consistent with reaching this high.
{{/if}}

Respond with:
- The 'locationName' for the forecast.
- An 'hourly' forecast array with exactly 12 items, covering the next 12 hours from the current time. Each item should include:
    - 'time': The specific hour (e.g., '3 PM', '10:00', 'Now', '1 hour from now').
    - 'temperature': Temperature in Celsius.
    - 'description': A brief textual description of conditions.
    - 'iconName': A simple weather condition name. Choose from: Sunny, Partly Cloudy, Cloudy, Light Rain, Drizzle, Light Snow, Foggy, Thunderstorm, Windy, Clear Night, Hail, Showers, Snowfall.
- A 'daily' forecast array with exactly 7 items, covering the next 7 days (including today). Each item should include:
    - 'day': Day of the week (e.g., 'Mon', 'Today', 'Tomorrow').
    - 'high': High temperature in Celsius for the day.
    - 'low': Low temperature in Celsius for the day.
    - 'description': A brief textual description of conditions for the day.
    - 'iconName': A simple weather condition name. Choose from: Sunny, Partly Cloudy, Cloudy, Light Rain, Drizzle, Light Snow, Foggy, Thunderstorm, Windy, Clear Night, Hail, Showers, Snowfall.

Ensure temperatures are realistic for the location and time of year.
If the location is very general, pick a major city within that area.
Example iconName values: "Sunny", "Partly Cloudy", "Rain", "Snowfall".
`,
});

const structuredWeatherForecastFlow = ai.defineFlow(
  {
    name: 'structuredWeatherForecastFlow',
    inputSchema: StructuredWeatherForecastInputSchema,
    outputSchema: StructuredWeatherForecastOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
